### ISSUE TITLE
Metabase: Power Bi open source alternative

### ISSUE THREAD

**Issue by Herbrant** [salvo-nicotra/tap#2]
I'd like to suggest an open source alternative to Power Bi, as I think that it could be useful for GNU/Linux users. It's called Metabase but I didn't  try it yet.
[Website](https://www.metabase.com/docs/latest/)
[Repo Github](https://github.com/metabase/metabase)

**Comment by nicshub** [comment]
I like the idea, let's use a case study to evaluate a new technology.
Salvo

**Comment by nicshub** [comment]
Let's use metabase!
